10.0/fake-ui: configure reporter,testgroups

diff --git a/servers/partner-ci/common.yaml b/servers/partner-ci/common.yaml
--- a/servers/partner-ci/common.yaml
+++ b/servers/partner-ci/common.yaml
@@ -198,6 +198,9 @@
           name: FUEL_QA_REFS
           description: "Multiple Refspecs for commits in fuel-qa gerrit separated with spaces"
       - string:
+          name: FUEL_WEB_REFS
+          description: "Multiple Refspecs for commits in fuel-qa gerrit separated with spaces"
+      - string:
           name: NAILGUN_HOST
       - string:
           name: ISO_JOB_BUILD_NUMBER
@@ -503,6 +506,70 @@
                     fail-on-missing: true
                     condition: FAILED_OR_BETTER
 
+- publisher:
+    name: fake-ui-publisher
+    publishers:
+      - postbuildscript:
+          script-only-if-succeeded: False
+          builders:
+            - shell: env > {properties_name}
+      - archive:
+          artifacts: '*.properties'
+          allow-empty: true
+      - archive:
+          artifacts: 'docker/fuel-ui/*.log'
+          allow-empty: true
+      - archive:
+          artifacts: 'docker/fuel-ui/test_run/**'
+          allow-empty: true
+      - email:
+          recipients: '{email_to}'
+      - description-setter:
+          regexp-for-failed: '^ERROR:.*'
+      - postbuildscript:
+          script-only-if-succeeded: False
+          script-only-if-failed: False
+          builders:
+            - shell:
+                !include-raw-escape: builders/ui.converter.sh
+            - shell: |
+                path=$(find docker/fuel-ui/test_run/ -name '*.xml')
+                python converter.py $path ${{WORKSPACE}}/nosetests.xml
+      - conditional-publisher:
+          - condition-kind: file-exists
+            condition-filename: 'nosetests.xml'
+            action:
+              - archive:
+                  artifacts: 'nosetests.xml'
+                  allow-empty: false
+      - junit:
+          results: '**/test_run/feature_nics/*.xml'
+          health-scale-factor: 1.0
+      - postbuildscript:
+          script-only-if-succeeded: False
+          script-only-if-failed: True
+          builders:
+              - shell: |
+                  [[ "${{DISCONNECT_ON_FAILURE}}" == "true" ]] && \
+                  python -c "import jenkins; jenkins.Jenkins(\"${{JENKINS_URL}}\", username=\"${{JENKINS_USERNAME}}\", password=\"${{JENKINS_PASSWORD}}\").disable_node(\"${{NODE_NAME}}\")"
+      - description-setter:
+          regexp-for-failed: '"error":(.*) \1 "AssertionError":(.*) \2'
+          description-for-failed: '\1 \2'
+      - slack:
+          notify-success: True
+          notify-failure: True
+          commit-info-choice: 'AUTHORS_AND_TITLES'
+          include-test-summary: True
+          build-server-url: 'http://jenkins-tpi.bud.mirantis.net:8080/'
+      - conditional-publisher:
+          - condition-kind: boolean-expression
+            condition-expression: "${{PUBLISH_RESULTS}}"
+            action:
+              - trigger-parameterized-builds:
+                  - project: '{reporter_name}'
+                    property-file: reporter.properties
+                    fail-on-missing: true
+                    condition: FAILED_OR_BETTER
 - builder:
     name: 10-get-refs
     builders:
@@ -546,6 +613,27 @@
             for ref in ${FUEL_QA_REFS:?}; do cherrypick $git_url $ref; done
           fi
 
+- builder:
+    name: 10-get-fake-ui-refs
+    builders:
+      - shell: |
+          #!/bin/bash
+          cherrypick() {
+              git_url=$1
+              ref=$2
+              git fetch $git_url "$ref" && git cherry-pick FETCH_HEAD || { git status; exit 1; }
+              git log --pretty=oneline | head
+          }
+          if [[ ! -z "${FUEL_UI_REFS}" ]]; then
+            cd ${WORKSPACE}/docker/fuel-ui
+            git_url=$(git config --get remote.origin.url)
+            for ref in ${FUEL_UI_REFS:?}; do cherrypick $git_url $ref; done
+          fi
+          if [[ ! -z "${FUEL_WEB_REFS}" ]]; then
+            cd ${WORKSPACE}/docker/fuel-web
+            git_url=$(git config --get remote.origin.url)
+            for ref in ${FUEL_WEB_REFS:?}; do cherrypick $git_url $ref; done
+          fi
 - builder:
     name: 10-get-zabbix-refs
     builders:
